language: java
jdk: openjdk11

script: mvn clean package

branches:
  except:
    - gh-pages

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    file_glob: true
    file:
      - target/*.jar
      - target/LICENSE
      - target/README.md
    on:
      tags: true
      all_branches: false

notifications:
  email:
    on_success: never
    on_failure: never
